import tkinter as tk
from tkinter import simpledialog, messagebox
import unicodedata
import re

def normalizar(texto):
    """Limpeza técnica interna para garantir que a comparação funcione."""
    if not texto: return ""
    # Remove acentos e converte para minúsculas
    texto = "".join(c for c in unicodedata.normalize('NFD', str(texto).lower().strip()) if unicodedata.category(c) != 'Mn')
    # Remove pontuação
    return re.sub(r'[^\w\s]', '', texto)

def tradutor_fisico(texto_usuario):
    # O sinal do usuário é limpo apenas para a lógica de busca
    sinal = normalizar(texto_usuario)
    
    # BANCO DE DADOS DE HARDWARE (OS 30 SENTIMENTOS)
    mapa_sentimentos = {
        "FOME": 
        ["fome", "estomago", "vazio", "roncando", "buraco na barriga", "fraqueza", "tontura de jejum", "salivando", "dor de cabeça de fome", "barriga roncando", "baixa energia", "tremedeira de fome", "estomago doendo", "falta de combustivel", "vontade de mastigar", "estomago contraindo", "visao escurecendo", "irritacao por fome", "hangry", "estomago alto", "vazio no tronco", "fraqueza nas pernas", "necessidade de glicose", "boca aguando", "salivacao excessiva", "pensando em comida", "estomago dando no", "sensacao de desmaio", "corpo sem sustento", "vontade de morder algo", "estomago sugando", "dor na boca do estomago", "falta de foco por fome", "abdomen retraido", "pontada de fome", "desejo calorico", "baixa de acucar", "corpo oco", "tronco vazio", "necessidade de mastigacao", "gosto de fome", "vontade de devorar", "energia em queda livre", "estomago acido", "fomi", "estomgo", "estumago", "bariga roncando", "buraqu no estomago", "vontade de kume", "preciso comer", "estomago vazio", "falta de comida", "querendo rango", "estomago gritando", "sem comer", "desmaio de fome", "fome de leao", "querendo morder a parede", "fomee", "estômgo", "estomgo doendo", "vontade de comer tudo", "estomgu", "buraquinho na bariga", "estomago vaziu", "precizo de comida", "fome de morre", "fomii", "hipoglicemia", "necessidade nutricional", "inanição", "estomgo roncand", "vazio no estomgo", "querendo cumida", "precizo cume", "fome extrema", "estomago doend", "fraqueza por falta de comida", "querendo mastigar algo", "estomago nas costas", "vontade de almocar", "vontade de jantar", "vntd d comer", "preciso d cmer", "fme", "estmgo", "estmg", "vntd d rango", "fomi d+", "fome dms", "fome braba", "preciso d glicose", "fome do kct", "fomr", "fomw", "estomaho", "estomafgo", "comer um boi", "estomago grudado nas costas", "morrendo de inanição", "estômago falando", "vazio por dentro no abdômen", "fome de mendigo", "preciso de sustento", "boca foi feita pra comer"],
       
        "SEDE": 
        ["sede", "boca seca", "garganta seca", "labios rachados", "lingua pegajosa", "vontade de beber", "secura", "desidratado", "garganta arranhando", "sede de deserto", "saliva grossa", "dificuldade de engolir", "boca de lixa", "vontade de algo gelado", "labio descascando", "urina escura", "sede que nao passa", "lingua branca", "garganta em carne viva", "desejo de agua", "interior seco", "pele ressecada", "necessidade hidrica", "lingua pesada", "garganta fechando de sede", "falta de agua", "vontade de molhar a boca", "secura nas mucosas", "lingua aspera", "gosto de poeira", "sedi", "garganta secaa", "preciso de agua", "querendo beber", "boca de gesso", "lingua seca", "secura na alma", "vontade de h2o", "boca colando", "garganta pegando fogo", "desidratacao", "falta de liquido", "copo d'agua", "seco por dentro", "garganta travada", "beber algo", "sedee", "boca de lixa", "garganta de deserto", "precizo de agua", "sedii", "boca ressecada", "garganta secaaa", "vontade d agua", "boca colada", "lingua de lixa", "desidratado", "xerostomia", "necessidade de hidratação", "garganta de poeira", "querendo h2o", "beber agua", "preciso d agua", "sese", "sece", "boca de deserto", "garganta em brasa", "lingua rachada", "sde", "vntd d beber", "preciso d h2o", "preciso d agua gld", "boca saca", "gargants", "gargnata", "swde", "ssde", "sedd", "sedee dms", "sedi d+", "preciso d líquido", "seco igual deserto", "garganta empoeirada", "virado em pó", "preciso de um gole", "boca pregando", "beber até o mar", "morrendo de sede", "interior esturricado", "pele de deserto"],
        
        "SONO / EXAUSTÃO":
        ["sono", "bocejo", "olho ardendo", "olho pesado", "pescoco caindo", "exaustao", "corpo moido", "fadiga", "sem energia", "bateria fraca", "querendo deitar", "palpebras pesadas", "corpo de chumbo", "moleza", "exausto", "morto de cansaco", "sem forcas", "visao embacada de cansaco", "coordenacao motora lenta", "corpo pedindo cama", "desligando", "sono pesado", "musculos moles", "olheira", "peso na nuca", "exaurido", "bocejando sem parar", "corpo arriado", "mente lenta", "falha de memoria por cansaco", "querendo fechar os olhos", "sono incontrolavel", "cansaco cronico", "exaustao fisica", "bracos pesados", "pernas arrastando", "vontade de apagar", "olhos fechando sozinhos", "pescoco sem forca", "moleza nos joelhos", "esgotamento total", "falta de ar de cansaco", "corpo derretendo", "sonoo", "bocejando", "cansaco", "cansado", "quero dormir", "morrendo de sono", "preciso de cama", "olho fechando", "corpo pesado", "exuastao", "exastao", "cançaso", "cansaso", "acabado", "destruido", "sem pilha", "sonolencia", "preguica de existir", "querendo cochilar", "sonuu", "exausto total", "corp moido", "olhos pesados", "morto de cansaço", "sono dms", "exaustãoo", "exausta", "exaustaum", "sonolento", "podre de sono", "letargia", "astenia", "exaustao severa", "corpo sem bateria", "sono absurdo", "precizo dormir", "morto de cansaço", "olho ardend", "exaustão física", "fadiga muscular", "querendo apagar", "olho fechando sozinho", "sono incontrolável", "sno", "snolento", "exausto dms", "acabado d+", "morto de cansaç", "sonooo", "sonn", "somno", "sonp", "soni", "exuastão", "exasutao", "cansadao", "canasdo", "cansadi", "preciso dmir", "quero dromir", "querendo dmit", "bat fraca", "sem bat", "pregar o olho", "morrendo de cansaço", "corpo de chumbo", "olhos de vidro", "pescoço de borracha", "sono de pedra", "desligar os motores", "cair de sono", "pescar de sono", "estar no bagaço", "estar no pó", "pedindo arrego", "preciso de um berço"],
       
        "MELTDOWN (CRISE EXTERNA)": 
        ["explodir", "quebrar", "gritar", "ferver", "faisca", "vontade de bater", "pressao na cabeca", "nao aguento mais", "irradiando raiva", "vontade de fugir", "chutar", "estourar", "incendio interno", "vulcao", "transbordando", "panela de pressao", "querendo morder", "rosto queimando", "perda de controle", "ficar cego de raiva", "maos tremulas", "vontade de destruir", "corpo eletrico", "pulso acelerado", "gritar de raiva", "estimulo excessivo", "curto-circuito motor", "querendo arrancar a pele", "agressividade fisica", "nervos a flor da pele", "querendo socar a parede", "visao vermelha", "corpo tremendo de furia", "perda de filtro", "vontade de arrancar o cabelo", "sobrecarga motora", "crise de choro e grito", "descontrole total", "gritar de pulmao cheio", "maos querendo agarrar algo", "tensao explosiva", "cabeca fervilhando", "frenesi fisico", "explodi", "vontade de quebra tudo", "querendo gritar", "perdi as estribeiras", "surto", "surtando", "nao me toca", "raiva descontrolada", "vontade de sumir", "nao aguento", "iaaaaaaa", "gritando", "quebrando", "estourando", "fervendo de odio", "colapso nervoso", "raiva fisica", "explodindo", "vou estourar", "nao aguento maisss", "meltdownn", "vontade de socar tudo", "gritaria", "quebradeira", "perder o controle", "surto psicotico", "raiva extrema", "desregulação emocional externa", "crise explosiva", "vontade de destruir tudo", "raiva visceral", "meltdon", "metldown", "vou esplodir", "vontade de chutar tudo", "rosto pegando fogo", "corpo em curto", "espiral de raiva", "surto de raiva", "gritando muito", "explod", "vou quebrar td", "vntd d bater", "nao aguento +", "nao aguento mms", "explodind", "surtand", "vou surtar", "vou surta", "explodirrr", "metdown", "meuudown", "surtoo", "raiva dms", "odio d+", "meltaown", "explodit", "exolodir", "quebrsr", "gritat", "sair do sério", "chutar o balde", "perder as estribeiras", "virar o bicho", "virar o capeta", "soltar os cachorros", "pisar no calo", "dar um chilique", "ficar possesso", "quebrar o pau", "sair de si", "sangue subindo", "perder a cabeça", "subir nas paredes", "espumar de raiva", "estar por um fio"],
       
        "SHUTDOWN (CRISE INTERNA)": 
        ["mudo", "sem fala", "nao consigo falar", "travado", "desligado", "congelado", "estatico", "paralisado", "olhar morto", "olhar fixo", "vazio por dentro", "anestesiado", "robotico", "marmorizado", "ausente", "embotado", "membros pesados", "sem reacao", "curto-circuito interno", "pensamento lento", "querendo ficar no escuro", "encolhido", "mente em branco", "dissipado", "vontade de sumir dentro de si", "desconexao total", "estado catatonico", "fala arrastada", "ouvindo mas nao processando", "incapaz de mover um dedo", "camera lenta", "atordoado", "corpo de pedra", "voz que nao sai", "sistema travado", "olhar perdido", "sentido unico de vazio", "encapsulado", "muralha interna", "isolado do mundo", "corpo de cimento", "mente offline", "travei", "desliguei", "nao sai som", "sem palavras", "bloqueado", "estatua", "mente vazia", "nao processando", "off", "fora do ar", "sumido", "encolhido", "catatonia", "mudez", "incapaz de falar", "shutdown", "chutdown", "lutdown", "travadao", "congelada", "shoudown", "desligada", "nao consigo abri a boca", "travadissimo", "estatico total", "mudez seletiva", "mente apagada", "fala zero", "retraimento social", "apatia profunda", "desregulação interna", "sistema offline", "paralizado", "estatua viva", "nao consigo me mover", "mente bloqueada", "sem resposta", "olhar pro nada", "ouvido desligado", "travada total", "chutidown", "shutidown", "shtdown", "off total", "desligad", "nao consigo flr", "n consigo flr", "travad", "congld", "congldo", "sem fl", "mudo dms", "shutdon", "shutdo", "shurdown", "shatdown", "travsdo", "congelaso", "desligaso", "mudo d+", "ficar na concha", "se fechar em copas", "engolir a seco", "ficar mudo igual uma porta", "estar em outro mundo", "perder o fio da meada", "ficar no seu quadrado", "entrar no casulo", "se trancar por dentro", "ficar que nem uma estátua", "mente no modo avião", "parecer uma parede", "estar no escuro", "cercado por muros", "vácuo interno"],
       
        "DISSOCIAÇÃO": 
        ["fora do corpo", "nevoeiro", "nuvem", "distante", "sonhando acordado", "irreal", "mundo de vidro", "nao me reconheco", "flutuando", "desconectado", "vendo de cima", "perdi o tato", "corpo de algodao", "sensacao de sonho", "piloto automatico", "dormente", "mente longe", "maos estranhas", "tempo paralisado", "desrealizacao", "vultos", "anestesia emocional", "corpo oco", "vendo a vida de longe", "perda de profundidade", "realidade distorcida", "parecendo um fantasma", "sem sentir dor fisica", "desconectado do ambiente", "flutuando no espaco", "maos irreais", "corpo sem peso", "sensacao de estar em um aquario", "mundo sem cor", "percepcao alterada", "fora de mim", "desreali", "sonho acordado", "flutuando", "corpo estranho", "nao sou eu", "vendo de fora", "desconectada", "distancia da realidade", "parece filme", "nevoa", "nevoa mental", "mente fora", "avoado", "disperso", "lugar nenhum", "despersonalizacao", "dissoçiacao", "fora da realidade", "parece sonho", "tudo irreal", "nao sinto meu corpo", "corpo de mentira", "flutuando no nada", "mente em outro lugar", "disociaçao", "despersonalização", "desrealização", "estado dissociativo", "sensação de bolha", "mundo irreal", "fora do eixo", "desconexo", "corpo mecanico", "mente distante", "disociaçao", "dissoçiaçao", "nuvem na cabeca", "nao me sinto aqui", "dissoç", "dissoc", "fora d mim", "nao so eu", "flutuand", "distnt", "irreal dms", "n me reconheço", "piloto auto", "disoç", "disoçiaçao", "dissisciaçao", "dissoaciação", "fora do cirpo", "fora di corpo", "flutuandp", "mebte longe", "estar no mundo da lua", "pisar em nuvens", "estar fora de órbita", "viver num aquário", "parecer um robô", "estar no automático", "se sentir um fantasma", "corpo sem alma", "estar em transe", "ver a vida passar em câmera lenta", "estar anestesiado pela vida", "não estar nem aí nem aqui", "sentir que a ficha não caiu", "estar num nevoeiro"],
       
        "ANSIEDADE / PÂNICO": 
        ["coracao", "taquicardia", "palpitacao", "falta de ar", "sufocando", "tremedeira", "mao suada", "formigamento", "no no estomago", "pavor", "vou morrer", "desespero", "tensao", "pernas bambas", "suor frio", "maos frias", "pes gelados", "falta de chao", "visao de tunel", "aperto no peito", "agonia", "maos tremulas", "bolo na garganta", "hiperventilacao", "sentindo o sangue pulsar", "dor no peito aguda", "medo de enlouquecer", "tontura subita", "calafrio na espinha", "frio no estomago", "respiracao curta", "musculos da face rigidos", "medo de perder o controle", "sensacao de desmaio iminente", "visao borrada", "formigamento no rosto", "maos dormentes", "querendo sair correndo", "pressao no torax", "ombros subindo", "aperto na garganta", "coracao batendo forte", "ansiedade", "crise de panico", "falta de ar", "tremendo", "sufocado", "angustia", "medo", "aperto", "coracao saindo pela boca", "tremedeira", "suando frio", "pânico", "panico", "anciedade", "ansiendade", "anxiedade", "corassaun", "peito apertado", "palpitaçao", "taquicardia forte", "ansiedade a mil", "pânicoo", "medo de morre", "falta de ar horrível", "tremendo muito", "angustya", "anciedadee", "coração aceleradíssimo", "crise de ansiedade", "ataque de pânico", "hiperventilação", "apreensão", "estado de alerta", "anciedade extrema", "coracao acelerado", "coracao pulando", "falta de ar constante", "corasao", "panico total", "medo de morrer agora", "ansid", "ancid", "coraca", "corasao", "tremend", "taquc", "pavor dms", "vou morre", "ansiedade d+", "anciedade dms", "ansiedadr", "ansiedsde", "ansiedaxe", "coracão", "coraçaoo", "palpitacoa", "palpitacaoo", "pnic", "pnc", "estar com o coração na mão", "ficar com os nervos à flor da pele", "sentir o chão sumir", "estar com o coração na boca", "ter um nó na garganta", "sentir o estômago dar voltas", "ficar com a pulga atrás da orelha", "estar em brasa", "ficar com as pernas de gelatina", "perder o fôlego", "sentir o mundo desabar", "estar por um fio", "beira de um colapso"],
       
        "SOBRECARGA SENSORIAL": 
        ["barulho", "luz", "cheiro forte", "etiqueta", "roupa pinicando", "muito som", "muita gente", "caos", "zumbido", "televisao alta", "poluicao visual", "toque indesejado", "agressao sonora", "irritacao tatil", "ambiente hostil", "ruido", "estatica", "tudo muito alto", "luz que doi", "cheiro enjoado", "pele sensivel demais", "muitos inputs", "bombardeio sensorial", "atordoado", "cheiros misturados", "pele queimando de toque", "dor sensorial", "sons cortantes", "luzes piscando na mente", "vontade de tapar os ouvidos", "mundo agressivo demais", "pele pinicando", "nervos expostos", "zumbido no ouvido", "cheiro de enxofre", "muita informacao visual", "muito barulho", "luz forte", "som alto", "cheiro ruim", "muito estimulo", "sensorial", "overload", "muita gente", "lugar barulhento", "luz incomodando", "som irritante", "toque chato", "pele sensivel", "agoniado com som", "irritacao visual", "muita luz", "barulhera", "zuada", "zumbido forte", "overload sensorial", "muita informaçao", "luzes fortes", "sons irritantes", "cheiro insuportável", "ambiente barulhento", "poluiçao sonora", "estatíca", "barulho dms", "hipersensibilidade sensorial", "bombardeio de estímulos", "irritação auditiva", "caos visual", "barulho insuportavel", "muito input", "barulhera", "luz q doi", "som q corta", "cheiro q enjoa", "senssorial", "muito barulhooo", "sensord", "ovrload", "mto barulho", "mta luz", "mto som", "overlod", "sensorial dms", "overload d+", "barulh", "brulho", "batulho", "luz forte dms", "mto estimulo", "senssorial", "barulhom", "barulhi", "mundo está gritando", "luz cortando os olhos", "estar numa centrífuga", "cérebro fritando", "sentir a pele em carne viva", "estar num ninho de vespas", "ruído branco insuportável", "luz que fura", "ser bombardeado por tudo", "estar numa feira livre", "sentir o som no osso", "ambiente me esmagando", "agulhadas nos ouvidos"],
       
        "INÉRCIA EXECUTIVA": 
        ["nao consigo comecar", "preso no sofa", "muro invisivel", "procrastinando", "estancado", "nao consigo levantar", "trava mental", "querendo fazer mas nao indo", "corpo colado", "paralisia de decisao", "motor travado", "sem arranque", "preso no loop", "corpo pesado demais", "falta de iniciativa fisica", "bloqueio motor", "caminho bloqueado na mente", "vontade sem acao", "incapacidade de trocar de tarefa", "mente quer corpo nao vai", "parado no tempo", "corpo imobilizado", "nao consigo fazer", "travado", "sem vontade de mover", "preso", "sem acao", "querendo mas nao conseguindo", "paralisado no sofa", "trava para fazer", "sem forca de vontade", "inercia", "inercia mental", "nao saio do lugar", "travadao", "procrastinacao", "bloqueado para agir", "inercia executiva", "nao consigo começar", "preso no lugar", "imobilizado mental", "trava pra agir", "corpo nao obedece", "mente travada", "sem impulsão", "parado sem conseguir sair", "disfunção executiva", "paralisia de análise", "incapacidade de ação", "travado no lugar", "sem conseguir começar", "bloqueio executivo", "motor mental travado", "não consigo mover", "inerçia", "executiva travada", "sem arranque mental", "inerc", "n consigo começar", "n consigo levntar", "preso no sf", "procrastinnd", "travad", "sem arrnque", "inercia dms", "executiva off", "muro invisivel dms", "inervia", "inerxia", "peeso no sofa", "travadi", "n consigofazer", "estar com as mãos atadas", "atolar na tarefa", "estar empacado", "nadar no seco", "não sair do zero", "estar preso em areia movediça", "motor que não pega", "ficar em banho-maria", "estar de braços cruzados contra a vontade", "empurrar com a barriga", "travado na largada", "muro de concreto invisível"],
       
        "BURNOUT (ESGOTAMENTO)": 
        ["fim da linha", "acabou a bateria", "morto por dentro", "peso de mil toneladas", "sem alma", "nada faz sentido", "exaustao cronica", "colapso", "nao tenho forca para o basico", "derretido", "esgotado", "pau no sistema", "sem processamento", "anemia de alma", "apagao", "corpo falhando", "cinzas", "sem motivacao biologica", "colapso funcional", "incapaz de processar um oi", "alma drenada", "bateria viciada", "corpo sem resposta", "desanimo organico", "fim de ciclo", "acabado", "sem vida", "esgotamento", "queimado", "fundo do poco", "sem rumo", "vazio", "zero energia", "corpo desligando", "mente queimada", "burnout", "esgotado mentalmente", "exaurido total", "sem pilhas", "pifado", "pifou", "bernout", "esgotamento total", "estafa", "fim de energia", "corpo pifado", "mente morta", "totalmente esgotado", "exaustao extrema", "sem alma nenhuma", "morto de cansaço", "esgotamento profissional", "colapso mental", "bateria social no zero", "drenado", "mente exausta", "burnoutt", "esgotado de tudo", "fim da energia total", "corpo e mente mortos", "sem processamento algum", "derretidissimo", "brnout", "bornout", "burnot", "fim d linha", "esgotad", "esgotdo", "sem bat", "bat no zero", "esgotamento dms", "burnout d+", "pifad", "morri p dentro", "burnour", "burnoutr", "burnoht", "esgotqdo", "exaustao total", "estar no limite", "chegar ao fundo do poço", "estar seco por dentro", "bateria viciada", "ser uma casca vazia", "jogar a toalha", "estar nas últimas", "estar no bico da chaleira", "ser um farrapo humano", "não ter onde cair morto", "alma no lixo", "esgotar a fonte", "corpo em cinzas"],
       
        "RSD (DISFORIA SENSÍVEL À REJEIÇÃO)": 
        ["ele me odeia", "falei errado", "mico", "me acham estranho", "rejeitado", "excluido", "dor de critica", "querendo sumir de vergonha", "humilhacao", "sentindo-se um peso", "ferida social", "alma exposta", "peito aberto", "dor de julgamento", "sentimento de lixo", "dor fisica de vergonha", "queimacao no peito social", "obsessao pelo erro cometido", "rejeicao fisica", "pontada no coracao social", "vontade de se esconder", "dor de reprovacao", "rejeicao", "vergonha", "me acham chato", "falei bosta", "ninguem gosta de mim", "sou um estorvo", "sou um peso", "me olharam torto", "falei merda", "querendo cavar um buraco", "sentindo-se mal por falar", "erro social", "julgamento", "critica doeu", "sentimento de exclusao", "rsd", "disforia de rejeição", "me sentindo rejeitado", "dor de julgamento", "vergonha extrema", "me acham ridículo", "todo world me odeia", "falei besteira", "rejeição social", "hipersensibilidade à crítica", "disforia sensível", "dor de ser excluído", "ferida emocional social", "rejeisao", "vergonha social", "me odeiam", "falei errado de novo", "critica me matou", "sentindo um lixo social", "rsd dms", "rejeitad", "excluid", "vergonh", "m acham chato", "m odeiam", "falei bst", "rsd d+", "dor de julgamento dms", "rsx", "rsc", "rejeisao", "regeisao", "me acham estrrnho", "falei erado", "levar um balde de água fria", "ficar com a cara no chão", "sentir uma facada no peito", "vontade de sumir do mapa", "ficar com o filme queimado", "ser a ovelha negra", "sentir que pisaram em mim", "vergonha de existir", "ficar pequeno de vergonha", "ser o patinho feio", "sentir que sou um estorvo", "falar para as paredes", "estar sobrando"],
       
        "TRISTEZA / ANGÚSTIA": 
        ["no na garganta", "vontade de chorar", "choro preso", "peito apertado", "triste", "melancolia", "solucando", "desanimado", "baixo astral", "nuvem cinza", "coracao pesado", "vazio no peito", "luto", "tristeza funda", "corpo sem osso", "vontade de ficar no quarto", "peso no coracao", "amargura", "falta de cor no dia", "dor na alma", "peito oco de dor", "alma cinzenta", "corpo pesado", "tristeza", "angustia", "chorando", "infeliz", "pra baixo", "desolado", "sem alegria", "deprimido", "tristeza profunda", "tristi", "vontade de chora", "coracao doendo", "alma triste", "tristesa", "angustya", "angusta", "tristee", "angustia profunda", "muito triste", "vontade de choraar", "melancolico", "coraçao doendo", "alma vazia", "tristezaa", "depressão", "desolação", "estado melancólico", "angustia no peito", "vazio profundo", "tristesza", "chorando muito", "coracao partido", "tristesa profunda", "angustiaa", "muita tristeza", "sem chao de tristeza", "trist", "angstia", "vntd d chorar", "triste dms", "angustia d+", "chorand", "tristez", "choro preso dms", "tristezaa", "teisteza", "trisreza", "tristrza", "tristeza profunda dms", "angustu", "angustiaa", "estar na fossa", "coração partido", "estar com a alma lavada de choro", "estar no fundo do poço", "viver um mar de rosas murchas", "alma em frangalhos", "chorar as pitangas", "céu de chumbo", "estar com o coração apertado", "vida sem cor", "sentir um vazio imenso", "ficar de luto pela vida", "estar na pior", "baixa astralidade"],
       
        "AFETO / AMOR": 
        ["coracao quente", "borboletas no estomago", "querer abracar", "carinho", "ternura", "admiracao", "saudade boa", "conexao", "querido", "acolhido", "quentinho", "paz no peito", "derretendo de amor", "sorriso bobo", "corpo relaxado", "vontade de cuidar", "peito expandindo", "vibracao suave", "calor interno", "pele relaxada", "seguranca fisica", "conforto no abraco", "batimento calmo", "amor", "carinho", "amado", "gostando", "apaixonado", "querer bem", "coracao leve", "afeto", "amizade", "abraço", "abracinho", "sentindo-se amado", "coracao bobo", "paz", "ternura", "carinhoso", "quentinho no coracao", "amoo", "muito amor", "carinhoso dms", "coração quentinho", "querer abraçar", "amizade pura", "afetivo", "amorzinho", "querido dms", "carinho fisico", "conexão emocional", "sentimento de pertença", "adoracao", "afetividade", "amorzão", "muito carinho", "coraçao quente", "amado demais", "quentinho na alma", "amr", "carinh", "vntd d abraçar", "coracao leve dms", "amado d+", "afeto dms", "querid", "amoor", "amo", "amlr", "amoe", "amir", "carunho", "carinhosoa", "amadooo", "queridoo", "estar nas nuvens", "coração batendo forte", "ser o porto seguro", "ficar de queixo caído", "encher o peito de alegria", "viver um conto de fadas", "ter o coração mole", "ser unha e carne", "ficar caidinho", "amor à primeira vista", "estar no céu", "chamego", "carinho na alma", "sentir-se em casa"],
       
        "HIPERFOCO / EMPOLGAÇÃO": 
        ["obcecado", "eletrizado", "nao consigo parar", "viciado na tarefa", "eureka", "brilhante", "energy alta", "uhu", "venci", "animado", "entusiasmado", "modo tunel", "vidrado", "focado", "pilhado", "acelerado", "hiperestimulado", "corpo vibrando", "nao piscar", "flow", "mente a mil", "dopamina", "efervescencia", "inquieto de alegria", "coracao saltitante", "sem sono de empolgacao", "foco total", "perda da nocao de tempo", "ligado no 220v", "vibracao nas maos", "visao focada", "pulso vibrante", "mente acelerada", "hiperfoco", "focado demais", "empolgado", "nao paro", "fissurado", "vidrado na tarefa", "foco maximo", "muito animado", "eletrico", "ligado", "mente voando", "fluxo total", "hiper foco", "iperfoco", "iperfoco", "vidradao", "muito loko", "hiper-foco", "animadissimo", "focado total", "mente a mil por hora", "dopamina pura", "flow total", "vibraçao forte", "vidradaum", "obsessão produtiva", "estado de fluxo", "excitação extrema", "focado dms", "super animado", "hiper-focado", "eletrizada", "focadaço", "mente a milhao", "empolgação total", "hperfoco", "iperfoco", "focad", "animad", "pilhad", "foco total dms", "eletric", "mente a mil d+", "hiper foco dms", "hiperfoco d+", "hiperfoc", "hiperfoxo", "hipergicp", "focadp", "pilhadp", "anomado", "estar a mil por hora", "ficar com a mente fervilhando", "mergulhar de cabeça", "ficar cego para o mundo", "estar no fluxo", "ser uma máquina", "estar com sangue nos olhos", "ficar ligado na tomada", "fogo nas vendas", "ir com tudo", "não tirar os olhos", "estar na zona", "mente em alta rotação"],
       
        "RAIVA": 
        ["odio", "mandibula presa", "punhos fechados", "calor subindo", "irritado", "bravo", "furioso", "querendo gritar", "sangue quente", "indignacao", "fervendo", "querendo rosnar", "explosivo", "pelos em pe", "ombros tensos", "dentes trincados", "respiracao pesada", "veia saltando", "vontade de socar", "irritabilidade", "corpo rigido", "olhar fixo de raiva", "maos fechadas", "calor no pescoco", "respiracao ofegante", "impaciencia fisica", "vontade de xingar", "ódio", "raiva", "irritada", "furiosidade", "brabeza", "querendo bater", "nervoso", "nervoso demais", "vontade de explodir", "odio mortal", "puto", "puto da vida", "com raiva", "mordendo os dentes", "trincado", "braveza", "raivaa", "odioo", "raiva extrema", "furioso dms", "irritadissimo", "querendo socar tudo", "fervendo de raiva", "bravo dms", "putasso", "puto dms", "fúria", "colera", "ira", "irritabilidade extrema", "com ódio", "brava", "muito bravo", "nervosíssimo", "raiva visceral", "braveza total", "puto da vvida", "odinho", "raivaa", "raiv", "odi", "irritad", "put d vida", "raiva dms", "odio d+", "bravo d+", "raivaa", "raov", "raia", "rsiva", "odioo", "pito", "putp", "putoo", "irratado", "irritsdo", "furiozo", "soltar fogo pelas ventas", "estar com a faca nos dentes", "ficar com sangue quente", "virar o bicho", "estar com a macaca", "subir o sangue", "ficar com a gota", "estar possesso", "trincar os dentes", "fechar o tempo", "roer as unhas de raiva", "estar com o diabo no corpo", "ficar de bico", "ficar com o cão"],
       
        "CONFUSÃO / OVERLOAD COGNITIVO": 
        ["nao entendi", "confuso", "perdido", "embaralhado", "muita coisa", "cerebro frito", "muitos dados", "labirinto mental", "sem logica", "travado no erro", "cabeca pesada", "chiado mental", "emaranhado", "inputs demais", "excesso de informacao", "curto circuito no cerebro", "pensamento atropelado", "incapaz de decidir", "nevoa mental", "brain fog", "ruido mental", "nao saquei", "entendi nada", "baguncado", "mente zoneada", "tudo misturado", "muita info", "confusao", "sobrecarga", "nao processa", "falha mental", "mente cheia", "cabeca dando tilt", "tiltou", "tiltou o cerebro", "nao consigo pensar", "overload cognitivo", "confusaum", "tudo bagunçado", "muito dado", "mente confusa", "nao entendi nada", "perdidaço", "cerebro travado", "tiltouu", "desorientação", "caos mental", "desorientado", "embaralhado dms", "mente bagunçada", "confuzao", "nao procesa", "muita coisa na cabeca", "cerebro frito dms", "confuso total", "perdidasso", "confus", "entendi nd", "n entendi nd", "n saquei nd", "bagunçd", "muita info dms", "confusao d+", "sobrecarga dms", "tiltad", "confsuo", "confuao", "comfuso", "confuzo", "embaralhaso", "perdidi", "perdido dms", "estar com a cabeça nas nuvens", "não saber onde se enfiar", "ficar com a cabeça fervendo", "dar um nó no juízo", "estar em um beco sem saída", "não falar lé com cré", "ficar boiando", "estar no mato sem cachorro", "perder a bússola", "estar com o tico e teco brigando", "confuso igual cego em tiroteio", "dar um nó no cérebro"],
       
        "MEDO / INSEGURANÇA": 
        ["frio na barriga", "incerto", "vigilante", "receio", "assustado", "pe atras", "com medo", "vulneravel", "ameacado", "arrepio na espinha", "sensacao de perigo", "corpo alerta", "instinto de fuga", "querendo se esconder", "olhando para os lados", "apreensivo", "coracao na boca", "instinto de preservacao", "vigilancia constante", "musculos prontos para correr", "medo", "receio", "com medo", "assustada", "inseguro", "com medo de algo", "preocupado", "vontade de fugir", "alerta", "perigo", "sentindo medo", "receioso", "cagaco", "medinho", "assustadissimo", "medoo", "medo constante", "perigo iminente", "com mto medo", "assustadissima", "medo de tudo", "receioso dms", "insegurançaa", "medo de falhar", "pavor", "temor", "insegurança profunda", "apreensividade", "vulnerabilidade", "com muinto medo", "ameaçado", "instinto de defesa", "medo de que algo aconteça", "perigo total", "medo extremo", "inseguroo", "med", "recei", "com md", "assustd", "preocupad", "medo dms", "inseguro d+", "medoo", "medr", "meso", "mexo", "mwd", "assuatado", "assustadi", "peeeigo", "perigoo", "receuoso", "ficar com o coração na mão", "estar com o rabo entre as pernas", "sentir o sangue gelar", "ficar de cabelo em pé", "estar com a pulga atrás da orelha", "tremer feito vara verde", "estar pisando em ovos", "sentir o estômago na garganta", "estar com o coração aos saltos", "morrer de medo", "ficar branco de susto", "sentir o calafrio da morte"],
       
        "ECOLALIA (REPETIÇÃO)": 
        ["repetindo", "frase na cabeca", "musica chiclete", "eco", "palavra viciante", "looping mental", "estimulacao sonora", "vicio de fala", "repeticao verbal", "ecolalia", "sons repetidos", "necessidade de repetir", "frase viciosa", "palatabilidade de palavras", "eco mental", "ecoando", "repetindo frase", "palavra na mente", "repeticao", "frase que nao sai", "musica repetindo", "eco de palavras", "ecoando na cabeca", "ecolalya", "repetindo sons", "fala repetida", "looping de fala", "viciado na palavra", "repetindo dms", "musica chicletee", "repetição vocal", "ecoando dms", "fala em looping", "repetição constante", "repetindo frases", "eco vocal", "estereotipia verbal", "ecolalia imediata", "frase em eco", "repetindo som", "palavra repetitiva", "ecolaliaa", "looping de palavra", "repetindo infinitamente", "eco constante", "palavra viciada", "repetind", "ecoand", "repetiç", "ecolalia dms", "frase repetindo d+", "musica repetind", "repetindooo", "repetinso", "repsitindo", "ecolslya", "ecoandp", "repetindo dms", "parecer um disco furado", "ficar como uma vitrola velha", "ecoar como um sino", "estar em looping", "repetir igual um papagaio", "frase colada no cérebro", "eco que não para", "mente repetidora", "vício de linguagem", "ficar na mesma tecla", "ser uma repetição sem fim"],
       
        "MAL-ESTAR FÍSICO": 
        ["enjoo", "nausea", "tontura", "dor no corpo", "latejando", "pontada", "mal estar", "indisposto", "corpo estranho", "instabilidade", "vontade de vomitar", "calafrio", "pressao baixa", "suor estranho", "corpo mole", "pontadas nas costas", "musculos doendo", "vomito", "dor visceral", "sensacao de doenca", "corpo pedindo pausa fisica", "desconforto gastrico", "mal-estar", "enjoado", "sentindo mal", "corpo ruim", "doente", "vontade de deitar", "fisicamente mal", "indisposicao", "enjo", "nauseas", "corpo moído", "mal estar fisico", "tonto", "tontura forte", "mau-estar", "enjoado dms", "sentindo-se doente", "corpo fraco", "nauseas fortes", "sentindo mal fisico", "indisposto dms", "enjou", "vomitoo", "disfunção física", "desconforto somático", "corpo instável", "mal estar geral", "sentindo-se mal", "corpo doendo muito", "enjoo forte", "nausea extrema", "tontura constante", "mal-estarzão", "corpo ruim dms", "corpo pedindo arrego", "enjo", "nause", "tontur", "mal estr", "mal estar dms", "enjoado d+", "tonto dms", "indispost", "enjoo dms", "enjoio", "enjjo", "tonturs", "tonturaa", "mal-estat", "mal-estat", "indisposyo", "vomitp", "estar no bagaço", "estar no pó da rabiola", "sentir-se como se um trator tivesse passado por cima", "estar mal das pernas", "virado do avesso", "estar com o corpo moído", "sentir-se um trapo", "estar para lá de Bagdá", "corpo fora do eixo", "sentir a vida pesando no corpo", "estar em frangalhos físicos"],
       
        "DOR DE CABEÇA / ENXAQUECA": 
        ["pressao nos olhos", "cabeca explodindo", "pulsacao na tempora", "luz doi", "martelada", "agulhada na cabeca", "cerebro pulsando", "peso na testa", "pontada no olho", "enxaqueca", "cabeca latejando", "nausea de dor", "dor na nuca", "pontadas cranianas", "visao com aura", "dor de cabeça", "dor de cabeca", "do de cabca", "dor di cabela", "dor de babeca", "cabeca doendo", "dor na cabeca", "enxaqueca forte", "cabeca pesada", "dor nos olhos", "martelando na cabeca", "cabeca pulsando", "dor de cabesa", "dor di cabeça", "do d cabeca", "dor de cabeçaa", "cabeca explodindo de dor", "enxaquecaa", "pressão na cabeça", "pulsando dms", "dor na testa", "dores de cabeça", "cabeça doendo muito", "cefaléia", "migrânea", "dor craniana", "pressão intracraniana", "pulsatilidade na cabeça", "cabeca martelando", "dor de cabeca dms", "enxaqueca braba", "cabeca explodindo total", "dor de cabeca infernal", "do d cabesa", "dor de cabç", "dr de cabeca", "cabeca doend", "enxaquec", "dor de cabeca d+", "enxaqueca dms", "dor d cab", "dor d cabc", "dor de cabaca", "dor de cabexa", "cabeca doebdo", "dor na cabesa", "enxqueca", "parece que tem um carpinteiro na minha cabeça", "cabeça vai rachar", "martelada constante", "pressão de mil atmosferas", "sentir o cérebro pulsar", "dor que cega", "cabeça de chumbo", "estar com a cabeça em brasas", "cérebro sendo esmagado", "luz que corta a cabeça", "martelada interna"],
       
        "NOJO / AVERSÃO": 
        ["nojo", "ascom", "ecat", "repugnante", "gosmento", "textura ruim", "cheiro de podre", "nausea sensorial", "arrepio de nojo", "vontade de cuspir", "pele arrepiada de asco", "repulsa fisica", "garganta fechando de nojo", "vontade de lavar a mao", "nojo total", "nojento", "eca", "credo", "textura estranha", "vontade de vomitar de nojo", "aversao", "asco", "repulsa", "que nojo", "cheiro ruim de nojo", "nojo de toque", "ecat", "nojinhu", "gosma", "nojoo", "ecati", "aversaum", "nojento dms", "repulsa total", "textura nojenta", "gosmento dms", "repugnancia", "asco total", "repulsa sensorial", "aversão física", "ojiza", "repugnância", "nojo de textura", "que nojooo", "nojento dmais", "aversao total", "vontade de vomitar nojo", "cheiro de podridão", "repulsa visceral", "noj", "asc", "nojent", "repulsa dms", "nojo d+", "aversao dms", "nojoo", "nojentooo", "nojinho dms", "nojento d+", "mojo", "molo", "nojentoa", "nojento", "nojewnto", "nojebto", "ecaaa", "embrulhar o estômago", "ficar com os pelos arrepiados", "sentir o estômago dar um nó", "dar ânsia de vômito", "ficar com o estômago embrulhado", "virar o nariz", "sentir ojeriza", "querer distância", "sentir nojo até da alma", "ter asco", "cheiro de morte", "textura de lama"],
       
        "CURIOSIDADE": 
        ["quero saber", "como funciona", "interessado", "pesquisando", "instigado", "descobrir", "investigando", "cacador de dados", "fome de saber", "explorando", "mente aberta", "busca de padrao", "curioso", "querendo entender", "investigando", "interessada", "buscando info", "como e", "porque", "querendo descobrir", "curiosidade", "buscando saber", "fome de dados", "instigada", "pesquisador", "investigador", "querendo saber dms", "muito curioso", "interessadissimo", "investigando tudo", "caçador de info", "querendo entender tudo", "curiosidadee", "interesse analítico", "investigação", "desejo de aprender", "instigação", "querendo saber o porque", "exploração mental", "curiosidade total", "interessado dms", "buscando padroes", "investigador de dados", "fome de conhecimento", "curiosid", "quero sbr", "como func", "interessad", "curioso dms", "curiosidade d+", "querendo sbr dms", "interessadissimo dms", "pesquisand", "curiosos", "curiozo", "curiso", "interessaso", "investiganso", "meter o nariz", "querer saber até onde a coruja dorme", "ficar com a pulga atrás da orelha", "desvendar o mistério", "ir fundo na questão", "caçador de pistas", "estar sedento por respostas", "não sossegar enquanto não descobrir", "mente de detetive", "querer ver com que olhos", "descobrir o X da questão"],
       
        "STIMMING (AUTORREGULAÇÃO)": 
        ["balancando", "maos agitadas", "girando", "maos balancando", "flapping", "pulando", "batendo o pe", "mexendo no cabelo", "mordendo a caneta", "preciso me mexer", "corpo pedindo ritmo", "balanco", "sacudindo", "esfregando as maos", "vocalizando", "apertando as maos", "balancar de cabeca", "necessidade de pressao", "andando sem parar", "estalando os dedos", "morder os labios", "balancar o tronco", "pressao profunda", "apertar objetos", "stimming", "estimming", "mexendo as maos", "balançando", "ritmo no corpo", "preciso de movimento", "flaping", "flapping de maos", "balanco de corpo", "auto estimulacao", "mexendo muito", "inquieto", "stiming", "maos balançando", "preciso de estimulo", "stimming dms", "balanço constante", "auto-estimulação", "movimento repetitivo", "flaping de mãos", "autorregulação sensorial", "estereotipias motoras", "busca sensorial", "preciso de stim", "movimento de autorregulação", "stimming constante", "mexendo o corpo", "preciso me balançar", "ritmo corporal", "balancando muito", "auto-estimulacao", "stim", "stimm", "balancand", "flaping", "stimming dms", "stimming d+", "preciso d movmnt", "stiming", "stimmung", "stiminh", "balancandp", "balancandoo", "flappingg", "balancando dms", "estar em transe motor", "corpo em balanço", "mãos que voam", "necessidade de sentir o ritmo", "corpo que dança sozinho", "ficar no seu balanço", "sentir o corpo no espaço", "mãos inquietas", "ficar em paz no movimento", "ritmo de proteção", "sentir a pressão do mundo"],
       
        "FRUSTRAÇÃO": 
        ["nao funcionou", "erro 404", "deu errado", "vontade de desistir", "irritado com erro", "output invalido", "travado no problema", "indignado", "insucesso", "impaciencia", "frustrado", "falha no codigo", "expectativa quebrada", "nao sai do lugar", "vontade de largar tudo", "frustracao", "nao deu certo", "merda de erro", "erro no sistema", "falhou", "nao vai", "travado no erro", "vontade de jogar tudo pro alto", "deu ruim", "falha", "insatisfeito", "erro fatal", "que odio de erro", "nao ta indo", "travado", "frustraçaoo", "deu errado dms", "frustradissimo", "nao funciona nada", "erro chato", "vontade de desistir total", "falhou dms", "frustração extrema", "insucesso total", "desapontamento", "sentimento de falha", "frustraçao braba", "deu tudo errado", "nao funcionou nada", "erro de processamento", "frustraçao total", "vontade de desistir de tudo", "frustaçao", "frustasao", "frust", "n funcionou", "n deu certo", "deu r", "frustrad", "erro d sistm", "frustracao dms", "frustrado d+", "frustado", "frustadao", "frustraçaoo", "deu erraso", "nao funcionpu", "frustradp", "frustrasaoo", "dar murro em ponta de faca", "ficar a ver navios", "quebrar a cara", "perder a paciência", "estar por aqui", "sentir o mundo contra mim", "dar com a cara no muro", "nadar, nadar e morrer na praia", "ficar de mãos abanando", "vontade de chutar o balde", "estar no limite da paciência", "frustração de código"],
       
        "INJUSTIÇA":
        ["absurdo", "antietico", "injusto", "quebra de logica", "erro de conduta", "revoltado", "quebra de expectativa", "falta de criterio", "injustica", "violacao de protocolo", "indignacao moral", "nao e justo", "erro de admin", "falha de carater externa", "injusto demais", "revolta", "absurdo total", "falta de etica", "quebra de regra", "nao pode ser", "errado", "muito errado", "injusitca", "injustissa", "quebra de confiança", "sem logica moral", "indignado", "injustiçaa", "revoltado dms", "anti-ético", "quebra de lógicaa", "indignação moral profunda", "totalmente injusto", "erro de ética", "violação de princípios", "injustiça ética", "moralmente errado", "falta de justiça", "injusto dms", "absurdo completo", "revoltado total", "sem ética alguma", "erro de justiça", "injustisça", "injustiçaa", "injust", "revoltad", "n e justo", "absurd", "injustiça dms", "injusto d+", "revoltado dms", "injustisa", "injustisaa", "absuado", "revoltqdo", "injusto dms total", "injustissq", "isso é um absurdo", "ser passado para trás", "fazer de bobo", "estar com a razão e ser ignorado", "pisar na bola comigo", "falta de caráter", "jogar sujo", "estar sendo injustiçado", "ser o bode expiatório", "fazer papel de palhaço", "isso não se faz", "quebra de valores", "injustiça moral"],
       
        "SOLIDÃO": 
        ["sozinho", "isolado", "sem conexao", "servidor unico", "falta de troca", "invisivel", "sem ninguem para falar", "vazio social", "desconectado de humanos", "solitario", "falta de pacotes sociais", "isolamento forcado", "sem par", "solidao", "sozinho no mundo", "sem amigos", "isolado de tudo", "solitaria", "sem contato", "vazio de gente", "necessidade social", "sem conversa", "sozinho total", "solidaoo", "solidao profunda", "sozinhoo", "isoladissimo", "sem ninguém", "vazio social dms", "solitário dms", "isolamento total", "falta de companhia", "sozinho de tudo", "desconexão social", "vazio interpessoal", "sentimento de isolamento", "solidão extrema", "solitario dms", "sem ninguem mesmo", "isolado do mundo", "vazio social total", "sem par social", "sozinho de verdade", "solidao profunda", "sozinh", "isolad", "solitari", "solidao dms", "sozinho d+", "isolado dms", "sozinhoo", "sozimho", "solidaom", "solidsao", "solidaooo", "sozinnho", "sozinhoo dms", "sozinho d+", "estar ao léu", "ser uma ilha", "sentir-se um deserto", "sozinho como um dedo", "estar na solidão da noite", "sem um ombro amigo", "falar com as paredes", "invisibilidade social", "sentir o vazio do mundo", "solidão que dói", "ser o único no mundo", "solidão absoluta", "isolado no seu universo"],
       
        "NÃO-VERBAL": 
        ["sem fala", "nao verbal", "voz nao sai", "modulo de audio off", "dificuldade de falar", "palavra some", "fala arrastada", "mudo temporario", "energia para falar zero", "nao quero falar", "comunicacao dificil", "bloqueio de fala", "nao consigo falar", "sem voz", "mudez temporaria", "nao-verbal", "fala bloqueada", "palavras fugiram", "incapaz de falar", "silencio total", "sem comunicacao", "voz sumiu", "nao quero papo", "nao-fala", "modulo off", "sem energia pra falar", "fala travada", "mudo total", "energia vocal zero", "nao quero fala", "afasia temporária", "bloqueio comunicativo", "vontade de não falar", "mudez de exaustão", "sem palavras para falar", "fala desligada", "bloqueio de voz", "não-verbalidade", "fala off", "mudo agora", "sem condicao de falar", "nao-verbal total", "n verbal", "sem fl", "voz n sai", "mudo dms", "n quero falar", "n verbal total", "fala off dms", "nao-verbl", "nao-verball", "nao-verbak", "sem dalar", "sem dslat", "n verbal dms", "ficar com a língua travada", "as palavras sumiram", "ficar mudo igual um peixe", "voz que não atravessa a garganta", "estar no silêncio profundo", "mudez de alma", "perder a voz interior", "bloqueio total de comunicação", "não sai nada", "estar em mudez seletiva por cansaço"],
       
        "ORGULHO / SUCESSO": 
        ["consegui", "venci", "eu fiz", "missao cumprida", "upgrade", "competente", "satisfeito com o codigo", "deploy funcional", "sensacao de dever cumprido", "eu sou bom nisso", "resultado positivo", "orgulho", "deu certo", "conseguido", "vitoria", "eu sou fera", "sucesso", "funciona", "orgulhoso", "vencedor", "fiz certo", "to bem nisso", "conseguim", "vencim", "funcionouuu", "conseguii", "conseguiii", "vitoriaa", "eu fiz isso", "orgulhoso dms", "sucesso total", "conseguido dms", "missao cumpridaa", "venci dms", "conquista pessoal", "auto-eficácia", "sucesso funcional", "triunfo", "fui bem", "resultado excelente", "consegui mesmo", "orgulho do trabalho", "deploy com sucesso", "venci o desafio", "conseguim total", "eu fiz bem feito", "orgulho dms", "conseg", "venc", "orgulhos", "sucesso dms", "orgulho d+", "consegui d+", "venci dms", "conseguu", "consequi", "conseguii", "vencii", "suceso", "orgulhoso dms total", "estar com a alma lavada", "lavar a égua", "ganhar o dia", "estar no topo do mundo", "ser o cara", "mandar bem", "dar um show", "tirar de letra", "acertar na mosca", "matar a cobra e mostrar o pau", "conquista de ouro", "orgulho de mestre", "dever cumprido com louvor"],
       
        "GRATIDÃO": 
        ["obrigado", "grato", "agradecido", "sorte", "backup positivo", "valorizar", "reconhecimento", "sentimento bom", "aliviado e grato", "reconhecer o bem", "gratidao", "valeu", "agradecida", "obrigada", "muito grata", "obrigadom", "obrigadao", "reconhecido", "grato por tudo", "obrigadu", "obrigadaaa", "valeu mesmo", "gratidaoo", "agradecidissimo", "obrigadão", "valeu dms", "muito grato", "gratidãum", "gratidãoo", "agradecida dms", "reconhecimento positivo", "apreço", "grata total", "obrigadissimo", "valeu de verdade", "agradecido dmais", "muito obrigada", "muito obrigado", "gratidao imensa", "agradecimento profundo", "valeu dms mesmo", "obrigadao total", "gratidaum", "obg", "vlw", "grat", "obrigad", "valeu dms", "gratidao d+", "valeu d+", "obrigadaa", "obg dms", "vlw dms", "valeuu", "obrigadom", "obrigadp", "obrigado dms", "agradescido", "agradeçido", "valru", "agradecer de coração", "estar com a alma grata", "reconhecer o valor", "ser grato até o fim", "dar graças", "gratidão que transborda", "reconhecer a mão amiga", "gratidão infinita", "estar em dívida de carinho", "coração agradecido", "muito obrigado mesmo"],
       
        "PAZ / HOMEOSTASE": 
        ["homeostase", "silencio", "calma", "equilibrio", "corpo leve", "mente limpa", "sem alertas", "estavel", "baixa latencia", "tranquilidade", "sistema em ordem", "paz", "tranquilo", "zen", "equilibrio total", "corpo em paz", "mente relaxada", "sem estresse", "tudo certo", "homeostasi", "sistema ok", "calmaria", "silencio mental", "estabilidade", "corpo calmo", "pazz", "tranquilidadee", "mente limpa dms", "equilíbrio", "homeostase total", "corpo estável", "paz interior", "calmaria total", "equilíbrio fisiológico", "estado de calma", "sistema em harmonia", "estabilidade interna", "paz absoluta", "calmo dms", "mente em paz", "corpo relaxado total", "homeostase perfeita", "tranquilidade absoluta", "equilíbrio mental", "paz total", "homeo", "paz dms", "tranquil", "estavl", "zen dms", "calm", "paz d+", "tudo ok", "tudo cert", "paz total dms", "homeostase dms", "homeostasw", "homeostasee", "pazz", "tranquiloo", "calmo dms total", "estar em águas calmas", "céu de brigadeiro", "corpo em harmonia", "silêncio de ouro", "estar na paz do senhor", "equilíbrio de mestre", "alma lavada e tranquila", "estar zen", "mar de rosas", "viver um dia de cada vez em paz", "estar com a mente em ordem", "paz de espírito"]
    }

    pontuacao = {}

    for categoria, termos in mapa_sentimentos.items():
        pontos = 0
        for termo in termos:
            termo_limpo = normalizar(termo)
            # A correção fundamental: verifica se a palavra-chave está dentro do que o usuário escreveu
            if termo_limpo in sinal:
                pontos += 1
        
        if pontos > 0:
            pontuacao[categoria] = pontos

    if not pontuacao:
        return "Sinal Desconhecido"

    # Retorna o sentimento que teve mais palavras correspondentes encontradas
    return max(pontuacao, key=pontuacao.get)

def executar():
    root = tk.Tk()
    root.withdraw()
    
    prompt = (
        "SISTEMA DE VARREDURA FÍSICA\n"
        "---------------------------\n"
        "Descreva detalhadamente o que você está sentindo no corpo agora:"
    )
    
    entrada = simpledialog.askstring("Input de Hardware", prompt)
    
    if entrada:
        # O resultado é apenas a string do sentimento (ex: "FOME")
        resultado = tradutor_fisico(entrada)
        
        # Exibe o diagnóstico limpo
        messagebox.showinfo("Diagnóstico de Varredura", f"Resultado da análise de sensores:\n\n>>> {resultado}")
    
    root.destroy()

if __name__ == "__main__":
    executar()
